name: 'Create Static Web App'
description: 'Create static web app'
inputs:
  name:
    required: true
    description: 'Static web app name'
  env:
    required: false
    default: 'stg'
    description: 'Environment of the static web app'
  creds:
    required: true
    description: 'Azure credential'
  region:
    required: false
    default: 'eastus2'
runs:
  using: composite
  steps:
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.creds }}
        allow-no-subscriptions: true
    - name: Static Web App Creation
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az staticwebapp create -n ${{ inputs.name }} -g '${{ inputs.region }}-${{ inputs.env }}'
          az staticwebapp secrets list --name ${{ inputs.name }}