name: test-app
on:
  push:
    branches: 
    - bla
concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true
jobs:
  createswa:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./actions/CreateStaticWebApp
      with:
        name: newswa
        creds: ${{ secrets.AZURE_CREDENTIALS }}

        